analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.267285
  brandStrength: 0
  lightness: 0.8591906
  brandColors:
    - '#8dc1e9'
    - '#cdd6d5'
    - '#000000'
    - '#4b4138'
    - '#756858'
  rhythmicContrast: 0.5067453
typography_spectrum: 0.5768281884957105
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3423271
favicon: null
name: design at mercurypc
