name: design at mercurypc
favicon: null
layout_spectrum: 0.35278
typography_spectrum: 0.5768281884957105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8dc1e9'
    - '#cdd6d5'
    - '#000000'
    - '#4b4138'
    - '#756858'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.6276090287137777
purpose: []
